"""
Pipeline — SpecOps 199 | DVCon India 2026 Stage 2A
===================================================
Implements the full block diagram from Stage 1 Proposal (Figure, pg 9):

  Input Image + Task Query
       |
       v
  [STAGE 1] Preprocessing — VEGA Processor (proposal §7)
       Resize + Normalize + BGR→RGB
       |
       v
  [STAGE 2] FPGA: CNN Backbone + Detection Head (proposal §8)
       EfficientNet feature extraction → bounding boxes + class + confidence
       (Software simulation: EfficientDet on CPU via ONNXRuntime)
       |
       v
  [STAGE 3] Processor: Task-Aware Scoring — VEGA CPU (proposal §9)
       Task Identification → Load W_t from DDR → score = x · W (dot product)
       |
       v
  [STAGE 4] Relative Thresholding (proposal §11)
       threshold = 0.80 × top_score → select all objects above threshold
       |
       v
  Final Task-Aware Output
"""

import cv2
import numpy as np
import os
import time
from task_vectors import TASK_WEIGHT_VECTORS, TASK_NAMES, TASK_KEYWORDS, CLASS_NAMES_COCO

N_CLASSES = 80


# ══════════════════════════════════════════════════════════════
# STAGE 1: Image Preprocessing  (Simulates VEGA Processor)
# Proposal §7: Resize → Normalize → Pixel scaling
# ══════════════════════════════════════════════════════════════
def stage1_preprocess(image_path: str) -> tuple:
    """
    VEGA Processor: Image preprocessing before FPGA inference.
    
    Operations (proposal §7):
      - Image resizing
      - Normalization
      - Pixel scaling

    Returns: (original_bgr_image, preprocessed_rgb_image)
    """
    print(f"\n  [STAGE 1 — Preprocessing | VEGA Processor]")

    original = cv2.imread(image_path)
    if original is None:
        raise FileNotFoundError(f"Cannot read image: {image_path}")

    # Resize → 512×512 (EfficientDet-D0 input)
    resized = cv2.resize(original, (512, 512))
    print(f"    Resize     : {original.shape[1]}×{original.shape[0]} → 512×512")

    # BGR → RGB
    rgb = cv2.cvtColor(resized, cv2.COLOR_BGR2RGB)

    # Normalize [0,255] → [0.0,1.0]
    normalized = rgb.astype(np.float32) / 255.0
    print(f"    Normalize  : pixel values → [0.0, 1.0]")
    print(f"    Done.")

    return original, rgb


# ══════════════════════════════════════════════════════════════
# STAGE 2: FPGA — CNN Backbone + Detection Head
# Proposal §8: EfficientNet feature extraction → detections
# (Software simulation on CPU via EfficientDet + ONNXRuntime)
# ══════════════════════════════════════════════════════════════
def stage2_fpga_detection(model, image_path: str,
                           conf_threshold: float = 0.25) -> list:
    """
    Simulates FPGA CNN Backbone + Detection Head (proposal §8).

    CNN Backbone (EfficientNet):
      Extracts: edges, textures, shapes, object patterns
      Operations: conv layers, BiFPN, feature maps

    Detection Head:
      Outputs: bounding boxes, class labels, confidence scores

    In Stage 3: this runs as INT8 bitstream on Digilent Genesys 2 FPGA.
    In Stage 2A: runs on CPU via EfficientDet + ONNXRuntime.

    Returns: list of { class_id, class_name, confidence, bbox, feature_vector }
    """
    print(f"\n  [STAGE 2 — CNN Backbone + Detection Head | FPGA simulation]")
    print(f"    Model      : EfficientDet (EfficientNet backbone + BiFPN)")
    print(f"    Inference  : CPU / ONNXRuntime (Stage 2A requirement)")

    t0 = time.time()
    raw_detections = model(image_path, conf_threshold=conf_threshold)
    elapsed = time.time() - t0

    if not raw_detections:
        print(f"    No objects detected (conf > {conf_threshold})")
        return []

    # Attach feature vectors (simulates FPGA backbone output transferred to CPU)
    # Proposal §9 step 5: "object feature vectors generated by FPGA transferred to processor"
    detected_objects = []
    for det in raw_detections:
        det["feature_vector"] = _build_feature_vector(
            det["class_id"], det["confidence"]
        )
        detected_objects.append(det)

    print(f"    Detected   : {len(detected_objects)} object(s) in {elapsed:.3f}s")
    for obj in detected_objects:
        print(f"      • {obj['class_name']:<20} conf={obj['confidence']:.3f}")

    return detected_objects


def _build_feature_vector(class_id: int, confidence: float) -> np.ndarray:
    """
    Builds 80-dim object feature vector x (proposal §9 step 5).
    In hardware: actual CNN feature map slice per detected region.
    In software: one-hot class encoding weighted by confidence score.
    Dimensionality = 80 = N_CLASSES, matching task weight vectors W_t.
    """
    vec = np.zeros(N_CLASSES, dtype=np.float32)
    if 0 <= class_id < N_CLASSES:
        vec[class_id] = confidence
    return vec


# ══════════════════════════════════════════════════════════════
# STAGE 3: VEGA Processor — Task-Aware Scoring
# Proposal §9 steps 3–6:
#   Task Identification → Load W_t → Feature Transfer → score = x · W
# ══════════════════════════════════════════════════════════════
def stage3_task_scoring(detected_objects: list, task_query: str) -> list:
    """
    Simulates VEGA Processor task-aware reasoning (proposal §9).

    Step 3 — Task Identification:
      Processor analyzes task description, compares with predefined task list,
      identifies Task ID.

    Step 4 — Task Weight Loading:
      Load W_t from DDR memory (TASK_WEIGHT_VECTORS dict simulates DDR storage).
      Example: Task ID = 10 → load W_10

    Step 5 — Feature Transfer:
      Object feature vectors already transferred from FPGA to CPU.

    Step 6 — Relevance Scoring:
      score = x · W  (dot product of feature vector and task weight vector)
    """
    print(f"\n  [STAGE 3 — Task-Aware Scoring | VEGA Processor]")
    print(f"    Task query : '{task_query}'")

    # Step 3: Task Identification
    task_id, task_name = _identify_task(task_query)
    print(f"    Task ID    : {task_id} ('{task_name}')")

    # Step 4: Load W_t from DDR memory
    W_t = TASK_WEIGHT_VECTORS[task_id]
    print(f"    Loaded     : W_{task_id} from DDR memory")

    # Steps 5+6: Feature Transfer + Relevance Scoring
    print(f"    Scoring    : score = x · W  (dot product)")
    scored = []
    for obj in detected_objects:
        x     = obj["feature_vector"]     # 80-dim object feature vector
        score = float(np.dot(x, W_t))    # proposal eq: score = x · W
        scored.append({**obj, "relevance_score": score})
        print(f"      • {obj['class_name']:<20} conf={obj['confidence']:.3f}  "
              f"relevance={score:.4f}")

    return scored


def _identify_task(task_query: str) -> tuple:
    """
    Proposal §9 Step 3: processor compares task with predefined task list.
    Uses keyword matching. Returns (task_id, task_name).
    """
    q = task_query.lower().strip()

    # Exact match first
    for tid, tname in TASK_NAMES.items():
        if q == tname.lower():
            return tid, tname

    # Keyword match
    for tid, keywords in TASK_KEYWORDS.items():
        if any(kw in q for kw in keywords):
            return tid, TASK_NAMES[tid]

    # Partial name match
    for tid, tname in TASK_NAMES.items():
        if tname.lower() in q or any(w in q for w in tname.lower().split()):
            return tid, tname

    print(f"    No exact match for '{task_query}', using Task 0 (general)")
    return 0, TASK_NAMES[0]


# ══════════════════════════════════════════════════════════════
# STAGE 4: Relative Thresholding
# Proposal §11: threshold = 0.80 × top_score
# ══════════════════════════════════════════════════════════════
def stage4_relative_threshold(scored_objects: list,
                               threshold_ratio: float = 0.80) -> list:
    """
    Proposal §11: Relative Thresholding.

    "Instead of selecting only one object, the system selects objects whose
     scores fall within a certain range of the highest score."

    Proposal example:
      Top score = 0.95, Threshold = 0.80
      wine glass (0.95) ✓ | cup (0.87) ✓ | others ✗

    Returns selected objects sorted by relevance score (descending).
    """
    print(f"\n  [STAGE 4 — Relative Thresholding]")

    if not scored_objects:
        print(f"    No objects to threshold.")
        return []

    top_score = max(o["relevance_score"] for o in scored_objects)
    threshold  = threshold_ratio * top_score

    print(f"    Top score  : {top_score:.4f}")
    print(f"    Threshold  : {threshold_ratio} × {top_score:.4f} = {threshold:.4f}")

    selected = sorted(
        [o for o in scored_objects if o["relevance_score"] >= threshold],
        key=lambda o: o["relevance_score"], reverse=True
    )
    rejected = [o for o in scored_objects if o["relevance_score"] < threshold]

    print(f"    Selected   : {len(selected)} object(s)")
    for o in selected:
        print(f"      ✓ {o['class_name']:<20} score={o['relevance_score']:.4f}")
    if rejected:
        print(f"    Rejected   : {len(rejected)} object(s) below threshold")
        for o in rejected:
            print(f"      ✗ {o['class_name']:<20} score={o['relevance_score']:.4f}")

    return selected


# ══════════════════════════════════════════════════════════════
# FULL PIPELINE — ties all 4 stages together
# Proposal block diagram: Input → §7 → §8 → §9 → §11 → Output
# ══════════════════════════════════════════════════════════════
def run_pipeline(image_path: str, task_query: str, model,
                 conf_threshold: float = 0.25,
                 threshold_ratio: float = 0.80,
                 save_output: bool = True) -> dict:
    """
    Full 4-stage pipeline as per Stage 1 proposal block diagram.

    Args:
        image_path:      Path to input image
        task_query:      Natural language task (e.g. "serve wine")
        model:           EfficientDetInferencer instance
        conf_threshold:  Detection confidence cutoff (default 0.25)
        threshold_ratio: Relative threshold ratio (proposal uses 0.80)
        save_output:     Save annotated image to outputs/

    Returns:
        dict with full results (for JSON report and video)
    """
    print("\n" + "═"*55)
    print("  SpecOps 199 — Task-Oriented Object Identification")
    print("  DVCon India 2026 | Stage 2A Pipeline")
    print("═"*55)
    print(f"  Image : {os.path.basename(image_path)}")
    print(f"  Task  : {task_query}")
    print("═"*55)

    t_start = time.time()

    # ── Stage 1: Preprocess ──────────────────────────────────
    original_img, _ = stage1_preprocess(image_path)

    # ── Stage 2: FPGA Detection ──────────────────────────────
    detected = stage2_fpga_detection(model, image_path, conf_threshold)

    if not detected:
        print("\n  [RESULT] No objects detected in image.")
        return _make_result(image_path, task_query, [], [], time.time()-t_start)

    # ── Stage 3: Task Scoring ────────────────────────────────
    scored = stage3_task_scoring(detected, task_query)

    # ── Stage 4: Relative Thresholding ──────────────────────
    selected = stage4_relative_threshold(scored, threshold_ratio)

    total_time = time.time() - t_start

    # ── Final Output ─────────────────────────────────────────
    print(f"\n  [FINAL OUTPUT]")
    if selected:
        primary = selected[0]
        print(f"  ✅ Primary  : {primary['class_name'].upper()}"
              f"  (relevance={primary['relevance_score']:.4f})")
        if len(selected) > 1:
            others = [o['class_name'] for o in selected[1:]]
            print(f"  ✅ Also     : {', '.join(others)}")
    else:
        print(f"  ⚠️  No task-relevant objects found.")
    print(f"  ⏱  Time    : {total_time:.3f}s")

    # ── Save annotated image ──────────────────────────────────
    out_path = None
    if save_output:
        out_path = _save_annotated(original_img, selected, scored,
                                   task_query, image_path)

    return _make_result(image_path, task_query, selected, scored,
                        total_time, out_path)


def _make_result(image_path, task_query, selected, all_scored,
                 elapsed, out_path=None) -> dict:
    return {
        "image":           os.path.basename(image_path),
        "task":            task_query,
        "pipeline_time_s": round(elapsed, 3),
        "primary_object":  selected[0]["class_name"] if selected else None,
        "selected_objects": [
            {"class": o["class_name"],
             "confidence": round(o["confidence"], 4),
             "relevance":  round(o["relevance_score"], 4),
             "bbox":       [round(v, 1) for v in o["bbox"]]}
            for o in selected
        ],
        "all_detections": [
            {"class": o["class_name"],
             "confidence": round(o["confidence"], 4),
             "relevance":  round(o["relevance_score"], 4)}
            for o in all_scored
        ],
        "output_image":    out_path,
        "status":          "success" if selected else "no_relevant_objects"
    }


def _save_annotated(original: np.ndarray, selected: list,
                    all_scored: list, task_query: str,
                    image_path: str) -> str:
    """
    Saves annotated image:
      GREEN box  = selected (task-relevant) objects
      RED box    = detected but not task-relevant
    """
    annotated = original.copy()

    selected_names = {o["class_name"] for o in selected}
    min_sel_score  = min((o["relevance_score"] for o in selected), default=0)

    for obj in all_scored:
        x1, y1, x2, y2 = [int(v) for v in obj["bbox"]]
        is_sel  = obj["class_name"] in selected_names
        color   = (0, 220, 0) if is_sel else (0, 0, 200)
        thick   = 3 if is_sel else 1
        cv2.rectangle(annotated, (x1, y1), (x2, y2), color, thick)
        label = f"{obj['class_name']} r={obj['relevance_score']:.2f}"
        (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.45, 1)
        cv2.rectangle(annotated, (x1, y1-th-4), (x1+tw, y1), color, -1)
        cv2.putText(annotated, label, (x1, y1-4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, (255, 255, 255), 1)

    # Task banner on top
    banner = f"Task: {task_query}"
    cv2.rectangle(annotated, (0, 0), (500, 32), (30, 30, 30), -1)
    cv2.putText(annotated, banner, (6, 22),
                cv2.FONT_HERSHEY_SIMPLEX, 0.65, (0, 255, 255), 2)

    out_dir = "outputs"
    os.makedirs(out_dir, exist_ok=True)
    base    = os.path.splitext(os.path.basename(image_path))[0]
    task_s  = task_query.replace(" ", "_")
    out_path = os.path.join(out_dir, f"{base}__{task_s}.jpg")
    cv2.imwrite(out_path, annotated)
    return out_path
